services: 
  frontend:
    build: frontend
    network_mode: "host"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  backend: 
    build: backend 
    ports: 
      - '8000:8000'
    volumes:
      - ./backend:/app
      - /app/.venv
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
    env_file:
      - ./backend/.env
  db:
    image: postgres:17
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:
