# Generated by Django 6.0.4 on 2026-05-30 08:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rows_count', models.PositiveIntegerField()),
                ('cols_count', models.PositiveIntegerField()),
                ('dolby_atmos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('producer', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('rating', models.CharField(max_length=10)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='screenings.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='screenings.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=7)),
                ('seat_number', models.IntegerField()),
                ('grid_x', models.PositiveIntegerField()),
                ('grid_y', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP')], default='REGULAR', max_length=10)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screenings.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=10)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='screenings.screening')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='screenings.seat')),
            ],
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('hall', 'row_label', 'seat_number'), name='unique_seat_per_hall'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('screening', 'seat'), name='unique_ticket_per_screening'),
        ),
    ]
