# Generated by Django 6.0.4 on 2026-06-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='salt',
            field=models.CharField(default='asfw9ef2', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='secret_hash',
            field=models.CharField(default='asfw9ef2', max_length=128),
            preserve_default=False,
        ),
    ]
