# Generated by Django 6.0.4 on 2026-06-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0003_remove_ticket_status_ticket_is_used_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='screenings.purchase'),
        ),
    ]
