# Generated by Django 6.0.4 on 2026-06-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0004_alter_ticket_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='screenings.purchase'),
        ),
    ]
