--
-- PostgreSQL database dump
--

\restrict qbh3NDyftPTdEsGg1OJ55Dj4ar9QxZuSgcDfxQAXq2PeYZNc6Fbj1qk5oOWOfmz

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg13+1)
-- Dumped by pg_dump version 17.7 (Debian 17.7-3.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO cinema;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO cinema;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    email character varying(254) NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    phone_number character varying(17) NOT NULL,
    date_of_birth date,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO cinema;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO cinema;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO cinema;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO cinema;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO cinema;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO cinema;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO cinema;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO cinema;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO cinema;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO cinema;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO cinema;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: screenings_hall; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.screenings_hall (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    rows_count integer NOT NULL,
    cols_count integer NOT NULL,
    dolby_atmos boolean NOT NULL,
    CONSTRAINT screenings_hall_cols_count_check CHECK ((cols_count >= 0)),
    CONSTRAINT screenings_hall_rows_count_check CHECK ((rows_count >= 0))
);


ALTER TABLE public.screenings_hall OWNER TO cinema;

--
-- Name: screenings_hall_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.screenings_hall ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.screenings_hall_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: screenings_movie; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.screenings_movie (
    id bigint NOT NULL,
    title character varying(100) NOT NULL,
    description text NOT NULL,
    producer character varying(100) NOT NULL,
    release_date date NOT NULL,
    duration interval NOT NULL,
    rating character varying(10) NOT NULL,
    poster_url character varying(200),
    genres character varying(200) NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.screenings_movie OWNER TO cinema;

--
-- Name: screenings_movie_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.screenings_movie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.screenings_movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: screenings_purchase; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.screenings_purchase (
    id bigint NOT NULL,
    status character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    paid_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    total_price numeric(10,2) NOT NULL,
    client_id bigint NOT NULL
);


ALTER TABLE public.screenings_purchase OWNER TO cinema;

--
-- Name: screenings_purchase_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.screenings_purchase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.screenings_purchase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: screenings_screening; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.screenings_screening (
    id bigint NOT NULL,
    start_time timestamp with time zone NOT NULL,
    base_price numeric(6,2) NOT NULL,
    hall_id bigint NOT NULL,
    movie_id bigint NOT NULL
);


ALTER TABLE public.screenings_screening OWNER TO cinema;

--
-- Name: screenings_screening_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.screenings_screening ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.screenings_screening_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: screenings_seat; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.screenings_seat (
    id bigint NOT NULL,
    row_label character varying(7) NOT NULL,
    seat_number integer NOT NULL,
    grid_x integer NOT NULL,
    grid_y integer NOT NULL,
    seat_type character varying(10) NOT NULL,
    hall_id bigint NOT NULL,
    CONSTRAINT screenings_seat_grid_x_check CHECK ((grid_x >= 0)),
    CONSTRAINT screenings_seat_grid_y_check CHECK ((grid_y >= 0))
);


ALTER TABLE public.screenings_seat OWNER TO cinema;

--
-- Name: screenings_seat_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.screenings_seat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.screenings_seat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: screenings_ticket; Type: TABLE; Schema: public; Owner: cinema
--

CREATE TABLE public.screenings_ticket (
    id bigint NOT NULL,
    price_paid numeric(6,2),
    created_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    screening_id bigint NOT NULL,
    seat_id bigint NOT NULL,
    salt character varying(8) NOT NULL,
    secret_hash character varying(128) NOT NULL,
    is_used boolean NOT NULL,
    purchase_id bigint NOT NULL
);


ALTER TABLE public.screenings_ticket OWNER TO cinema;

--
-- Name: screenings_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: cinema
--

ALTER TABLE public.screenings_ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.screenings_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account_emailaddress; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.account_emailaddress (id, email, verified, "primary", user_id) FROM stdin;
2	test@tester.com	f	t	6
3	new@guy.com	f	t	7
\.


--
-- Data for Name: account_emailconfirmation; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.account_emailconfirmation (id, created, sent, key, email_address_id) FROM stdin;
\.


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.accounts_user (id, password, last_login, is_superuser, email, first_name, last_name, phone_number, date_of_birth, is_active, is_staff) FROM stdin;
31	pbkdf2_sha256$1200000$UxWXaQ1RaXjLlAYFHZodhx$B+jZAqS+THhkLWxmkGpCrChcUuTDVVfEYmrdJ18IJuM=	\N	f	charlie.d@example.com	Charlie	Davis	+15550177	2005-04-15	t	f
32	pbkdf2_sha256$1200000$Ds3ZT35t6pxW9pAht9SMJR$vqsnQVCGpK3uTgfhvFI+d2BpiFQaw27EWQZXvJT7+R8=	\N	f	diana.p@example.com	Diana	Prince	+15550965	2004-08-17	t	f
7	pbkdf2_sha256$1200000$FwX5o3oHDLD7GZYKiLndfF$o0jdCv0IR+yNSwcfqCatiW3vuFI7uocHIOHFy3LAtgs=	2026-05-30 10:12:13.797232+00	f	new@guy.com	New	Guy	+300987654321	2001-10-04	t	f
33	pbkdf2_sha256$1200000$otWubEwADZq6lt4aL41fwH$qt65t5qTtTktf6JGuao4HGE46EDlpYPp/R9aknW1GZE=	\N	f	ethan.h@example.com	Ethan	Hunt	+15550789	2003-11-24	t	f
34	pbkdf2_sha256$1200000$xUZvRq24TYDfEM3o7mPDTz$U8PtWOYOI72m2xum8KbROyDPVMUy7iw1zcjTu7TjF20=	\N	f	fiona.g@example.com	Fiona	Gallagher	+15550892	1995-02-10	t	f
35	pbkdf2_sha256$1200000$KXR03GBCnsPJjQW9W7sRLb$nD/kAz/XureDUj2/ZvIK/OUb465d/HRXE3cbluZT+WQ=	\N	f	george.c@example.com	George	Clark	+15550600	1979-11-09	t	f
8	pbkdf2_sha256$1200000$av8q9n9ImorGTuRNP97Rx5$u48vB9jBMD6rULB2CRnSyKRNHgOenIz7ZN4dJdgUSrA=	\N	t	admin@cinema.com	Admin	User	+1234567890	1990-01-01	t	t
9	pbkdf2_sha256$1200000$pOIUi7jnTYo9jQzfttG7Zl$vHGuhQGJcU5rBp4dfvZZ3E0KJHsZf2/uOGycEe388dI=	\N	f	jdoe@example.com	John	Doe	+1555010101	1985-05-15	t	f
10	pbkdf2_sha256$1200000$r9dn2Ln1CnYi75U4CeZLp8$2GWgJJVI8eDhULEE1B4rK0ZIigsgOfv/XIi7nT/WItg=	\N	f	asmith@example.com	Adam	Smith	+1555020202	1995-10-20	t	f
36	pbkdf2_sha256$1200000$8l1y0XK6U8LoiRPt55Vjnr$q5n7OVDzq5ew6XeOXodGbr/ghjUnR3e+EdKT3VQA2BA=	\N	f	hannah.b@example.com	Hannah	Baker	+15550599	1995-05-27	t	f
6	pbkdf2_sha256$1200000$7nZ1Xi3y1c44BJijGp79bF$jj5xsuHxhGOI0yTDN0fkaCFiKJXaoqjvByznh4T08Cs=	2026-06-04 08:23:41.456383+00	f	test@tester.com	Test	Tester	+301234567890	\N	t	f
37	pbkdf2_sha256$1200000$coIrwYx1Ya0VpiMNZ40UVl$ZLW7/RUAIrAg923t8sHMj2Wh+s3nT01EOUn7tCDFFxU=	\N	f	ian.m@example.com	Ian	Malcolm	+15550560	1989-03-26	t	f
38	pbkdf2_sha256$1200000$Xl4OEyvA9Vn45iVdgfO0Zq$LDX2seEs0oyHWZlAyWQyEBiDQWRdeP6oywi2qD6vLrU=	\N	f	julia.r@example.com	Julia	Roberts	+15550925	1978-02-14	t	f
4	pbkdf2_sha256$1200000$NdMQDBHlpXQP44BnJRYlM3$fOf9N30b4aZugf1JuDMVRaFRgvZGHeiKGJXP0UInc4M=	2026-06-29 07:41:06.350854+00	t	soulgeo01@gmail.com	George	Soulantikas	+306978075068	\N	t	t
29	pbkdf2_sha256$1200000$3qU37VBNgKP8KvzCa5pu2O$rRCt8OAW+EzC+V4SDxJZbcS2ac1J6lZmn4YDTANUDPw=	\N	f	alice.w@example.com	Alice	Ward	+15550151	2001-05-13	t	f
30	pbkdf2_sha256$1200000$NLVlf5C78Dp4d6tekdz0bi$QPoaHEZI6KBxbSZ6mya2On7HRtKxKFLZJBRbeuwWAJE=	\N	f	bob.m@example.com	Bob	Miller	+15550266	1979-12-22	t	f
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
1	8	2
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.auth_group (id, name) FROM stdin;
1	Staff
2	Admin
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add site	6	add_site
22	Can change site	6	change_site
23	Can delete site	6	delete_site
24	Can view site	6	view_site
25	Can add email address	7	add_emailaddress
26	Can change email address	7	change_emailaddress
27	Can delete email address	7	delete_emailaddress
28	Can view email address	7	view_emailaddress
29	Can add email confirmation	8	add_emailconfirmation
30	Can change email confirmation	8	change_emailconfirmation
31	Can delete email confirmation	8	delete_emailconfirmation
32	Can view email confirmation	8	view_emailconfirmation
33	Can add user	9	add_user
34	Can change user	9	change_user
35	Can delete user	9	delete_user
36	Can view user	9	view_user
37	Can add hall	10	add_hall
38	Can change hall	10	change_hall
39	Can delete hall	10	delete_hall
40	Can view hall	10	view_hall
41	Can add movie	11	add_movie
42	Can change movie	11	change_movie
43	Can delete movie	11	delete_movie
44	Can view movie	11	view_movie
45	Can add screening	12	add_screening
46	Can change screening	12	change_screening
47	Can delete screening	12	delete_screening
48	Can view screening	12	view_screening
49	Can add seat	13	add_seat
50	Can change seat	13	change_seat
51	Can delete seat	13	delete_seat
52	Can view seat	13	view_seat
53	Can add ticket	14	add_ticket
54	Can change ticket	14	change_ticket
55	Can delete ticket	14	delete_ticket
56	Can view ticket	14	view_ticket
57	Can add purchase	15	add_purchase
58	Can change purchase	15	change_purchase
59	Can delete purchase	15	delete_purchase
60	Can view purchase	15	view_purchase
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-05-30 09:53:14.223781+00	5	test@tester.com	3		9	4
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	sites	site
7	account	emailaddress
8	account	emailconfirmation
9	accounts	user
10	screenings	hall
11	screenings	movie
12	screenings	screening
13	screenings	seat
14	screenings	ticket
15	screenings	purchase
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-30 08:41:43.057125+00
2	contenttypes	0002_remove_content_type_name	2026-05-30 08:41:43.062033+00
3	auth	0001_initial	2026-05-30 08:41:43.078+00
4	auth	0002_alter_permission_name_max_length	2026-05-30 08:41:43.082302+00
5	auth	0003_alter_user_email_max_length	2026-05-30 08:41:43.086947+00
6	auth	0004_alter_user_username_opts	2026-05-30 08:41:43.091479+00
7	auth	0005_alter_user_last_login_null	2026-05-30 08:41:43.096082+00
8	auth	0006_require_contenttypes_0002	2026-05-30 08:41:43.098107+00
9	auth	0007_alter_validators_add_error_messages	2026-05-30 08:41:43.102695+00
10	auth	0008_alter_user_username_max_length	2026-05-30 08:41:43.107232+00
11	auth	0009_alter_user_last_name_max_length	2026-05-30 08:41:43.111802+00
12	auth	0010_alter_group_name_max_length	2026-05-30 08:41:43.116543+00
13	auth	0011_update_proxy_permissions	2026-05-30 08:41:43.121053+00
14	auth	0012_alter_user_first_name_max_length	2026-05-30 08:41:43.125733+00
15	accounts	0001_initial	2026-05-30 08:41:43.139714+00
16	account	0001_initial	2026-05-30 08:41:43.155326+00
17	account	0002_email_max_length	2026-05-30 08:41:43.162236+00
18	account	0003_alter_emailaddress_create_unique_verified_email	2026-05-30 08:41:43.173334+00
19	account	0004_alter_emailaddress_drop_unique_email	2026-05-30 08:41:43.18367+00
20	account	0005_emailaddress_idx_upper_email	2026-05-30 08:41:43.201011+00
21	account	0006_emailaddress_lower	2026-05-30 08:41:43.20995+00
22	account	0007_emailaddress_idx_email	2026-05-30 08:41:43.221474+00
23	account	0008_emailaddress_unique_primary_email_fixup	2026-05-30 08:41:43.230836+00
24	account	0009_emailaddress_unique_primary_email	2026-05-30 08:41:43.237627+00
25	admin	0001_initial	2026-05-30 08:41:43.249804+00
26	admin	0002_logentry_remove_auto_add	2026-05-30 08:41:43.256431+00
27	admin	0003_logentry_add_action_flag_choices	2026-05-30 08:41:43.26327+00
28	screenings	0001_initial	2026-05-30 08:41:43.302019+00
29	sessions	0001_initial	2026-05-30 08:41:43.307874+00
30	sites	0001_initial	2026-05-30 08:41:43.311425+00
31	sites	0002_alter_domain_unique	2026-05-30 08:41:43.315508+00
32	accounts	0002_alter_user_date_of_birth	2026-05-30 08:45:29.994468+00
33	accounts	0003_alter_user_date_of_birth	2026-05-30 08:46:50.734441+00
34	screenings	0002_ticket_salt_ticket_secret_hash	2026-06-02 09:18:07.952298+00
35	screenings	0003_remove_ticket_status_ticket_is_used_purchase_and_more	2026-06-04 11:40:18.124601+00
36	screenings	0004_alter_ticket_purchase	2026-06-04 11:40:18.142155+00
37	screenings	0005_alter_ticket_purchase	2026-06-04 11:40:18.157316+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
hsw3dv6gld5q5v6dbbdkwnvp6gdtb2bc	.eJxVjEEOwiAQRe_C2hCgZaAu3fcMZAYGqRqalHZlvLtt0oVu_3vvv0XAbS1ha7yEKYmr6MXldyOMT64HSA-s91nGua7LRPJQ5EmbHOfEr9vp_h0UbGWvo1EMPkLKftBZJwJ2yBkQ2DjfuQ4t5l2ImnqvaPBJgSIy4EFba534fAH93Dfm:1wTFM8:jusQzdJdrI7yGE28hycfPGJ30dTAsnWG_Dv8Ul2hB4k	2026-06-13 08:47:44.305343+00
wftqmsuwvrad119zi1p7l9tf4p4uj57v	.eJxVjbFuhDAQRP9la4RsA_ZCFaXPF0QRWtsLOAE7wkYpTvfvgeSa60Yzb2ZuQM6lI5aRjrJwLMFRCSmOG5cl-QzD-w3-NQzwTTn_pN1DBVRgkAaVkYha102rJPZNBbxRWE80p2OdOQn5Ml9O7dIG948K_n7GI_M-hmuyhSfPkvvieAX-k-Kczl4se7D1hdSPNNdvyfP6-mCfBhbKy9l2SrBGp_2EvZykt5oN8aRJszLYmIY6mk7ASduisD16oYW1SqOWXdcZuP8CIT1csg:1we6c6:LNJPFzgdXTrFmPZ_MnaaXG7e_CSsP1eFwbNlhMiIkMw	2026-07-13 07:41:06.353552+00
irlypks5ppd3lnw0t7x5p090qq8203a5	.eJxVjEEOwiAQRe_C2hCgZaAu3fcMZAYGqRqalHZlvLtt0oVu_3vvv0XAbS1ha7yEKYmr6MXldyOMT64HSA-s91nGua7LRPJQ5EmbHOfEr9vp_h0UbGWvo1EMPkLKftBZJwJ2yBkQ2DjfuQ4t5l2ImnqvaPBJgSIy4EFba534fAH93Dfm:1wTG3i:gKVVxukOgFWW0TtWxXyFI4LdyrMydRKdKLqy-NIAS8k	2026-06-13 09:32:46.392311+00
co9gs7jwvqtgij9c918o183q3te154xw	.eJxVjc1uwyAQhN9lzxYCE_PjU5V7nyCKrAWWmjaGymD1EOXda7e55DJazXwzewf0vmy5Tbi1mXJLHlsqeVqozSVUGC93-L9hhG-s9aesATrABqPQhksprenZoIwQ1nRAC6bbjjaq7e0QWpkvCzyuHfz9mLZK65SOOQUvnkP_RfkIwifmj7L3cluTYwfCnmll7yXQ7fxkXwZmrPPeJsV5DFaF2LsoBmX7wWkXvRWajNdIXAYdRG9PIjp3UnFAY7lwVnKvlUR4_ALS9FvH:1wU6CE:o54LmxUjU9ufid_aXurwSvhcE6vL7_YpIymctpNbm_4	2026-06-15 17:13:02.578882+00
jgy5idcbr0iuimwxng17slkfreb9g55g	.eJxVjcFugzAQRP9lzwjZgNcOp6r3fkEVobW9gFuwK2yUQ5R_L7S55DaaeTNzB3Iu7bEMtJeZYwmOSkhxWLnMyWfoP-_wr6GHH8r5ljYPFVCBXmojW9UogbVGpbGrgFcKy0HmtC8TJyHfptOpXVrhca3g72bYM29DOBc7ePEsuW-OZ-C_KE7p6MWyBVufSP1Mc_2RPC_vT_ZlYKY8H23XCEbj0I_mIkfpLbImHpGQG21a3ZKi8QCctJ0R9mK8QGFtgwalUkrD4xfXvlx3:1wYNA2:CaBRExYsjjXdVgedy_u0StofA5ilU3i6OS4CMyr5CgA	2026-06-27 12:08:26.77589+00
\.


--
-- Data for Name: django_site; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.django_site (id, domain, name) FROM stdin;
1	example.com	example.com
\.


--
-- Data for Name: screenings_hall; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.screenings_hall (id, name, rows_count, cols_count, dolby_atmos) FROM stdin;
1	Grand IMAX	12	16	t
2	Screen 1	8	12	f
3	Screen 2	8	12	f
4	VIP Lounge	4	6	t
5	Kids Zone	6	10	f
\.


--
-- Data for Name: screenings_movie; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.screenings_movie (id, title, description, producer, release_date, duration, rating, poster_url, genres, is_active) FROM stdin;
231	Project Hail Mary	An astronaut tries to save Earth while alone in outer space.	Phil Lord, Christopher Miller	2026-03-20	02:15:00	PG-13	https://image.tmdb.org/t/p/w500/yihdXomYb5kTeSivtFndMy5iDmf.jpg	Sci-Fi, Adventure	t
232	The Super Mario Galaxy Movie	Mario and friends travel through space to save the galaxy.	Chris Meledandri	2026-04-01	01:45:00	PG	https://image.tmdb.org/t/p/w500/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg	Animation, Adventure, Comedy	t
233	Lee Cronin's The Mummy	A new take on the ancient Egyptian curse.	Lee Cronin	2026-04-17	01:55:00	R	https://image.tmdb.org/t/p/w500/uIb9Tvae5haF0XcQBaPyufmxbb0.jpg	Horror, Fantasy, Action	t
234	Michael	The definitive biopic of the King of Pop, chronicling his rise from the Jackson 5 to global superstardom.	Graham King, Antoine Fuqua	2026-04-24	02:30:00	PG-13	https://glamournepal.com/wp-content/uploads/2025/11/Michael-Biopic-Film-Poster-2026.jpg	Drama, Music, History	t
235	The Devil Wears Prada 2	Miranda Priestly struggles to keep Runway magazine relevant while Andy and Emily navigate new roles in a digital world.	Wendy Finerman, Karen Rosenfelt	2026-05-01	01:59:00	PG-13	https://cdn.moviefone.com/admin-uploads/highlights/images/the-devil-wears-prada-2-character-poster-emily-blunt_1770059722.webp	Comedy, Drama	t
236	Mortal Kombat II	The tournament continues with new fighters and higher stakes.	James Wan	2026-05-08	02:10:00	R	https://image.tmdb.org/t/p/w500/lIsMeDbwntNXSUVHmWMMRXEZOVc.jpg	Action, Fantasy	t
238	In the Grey	A covert team of elite operatives specializes in recovering stolen assets from a ruthless despot.	Guy Ritchie, Ivan Atkinson	2026-05-15	01:37:00	R	https://cdn.moviefone.com/admin-uploads/highlights/images/in-the-grey-official-poster_1773945137.webp	Action, Thriller, Drama	t
239	The Mandalorian and Grogu	Din Djarin and Grogu embark on a mission to rescue Rotta the Hutt for the New Republic.	Jon Favreau, Kathleen Kennedy, Dave Filoni	2026-05-22	02:12:00	PG-13	https://cdn.moviefone.com/admin-uploads/highlights/images/star-wars-the-mandalorian-and-grogu-official-poster_1771351937.webp	Action, Adventure, Sci-Fi	t
240	Backrooms	A furniture store owner discovers a portal to a dimension of endless yellow-walled liminal spaces.	James Wan, Shawn Levy, Peter Chernin	2026-05-29	01:45:00	R	https://mlpnk72yciwc.i.optimole.com/cqhiHLc.IIZS~2ef73/w:auto/h:auto/q:75/https://bleedingcool.com/wp-content/uploads/2026/03/BACKROOMS-Payoff-Poster-2.jpg	Horror, Sci-Fi	t
241	Masters of the Universe	Prince Adam / He-Man must protect Eternia from the dark forces of Skeletor.	Travis Knight	2026-06-05	02:05:00	PG-13	https://cdn.kinocheck.com/i/93nua8uz97.jpg	Action, Fantasy, Adventure	t
242	Scary Movie	The original cast returns to parody modern "elevated horror" hits and pop culture trends.	Wayans Brothers, Neal H. Moritz	2026-06-05	01:35:00	R	https://cdn.moviefone.com/admin-uploads/highlights/images/scary-movie-official-poster_1778000082.webp	Comedy, Horror, Parody	t
243	Disclosure Day	A targeted whistleblower races against time to reveal the truth about extraterrestrial visitors.	Steven Spielberg, Kristie Macosko Krieger	2026-06-12	02:25:00	PG-13	https://cdn.moviefone.com/admin-uploads/highlights/images/disclosure-day-official-poster_1773337616.webp	Sci-Fi, Thriller, Drama	t
244	Toy Story 5	Woody, Buzz, and the gang return for another adventure.	Andrew Stanton	2026-06-19	01:40:00	G	https://image.tmdb.org/t/p/w500/i4UtdsApMwXQkGD2mBDroJSJZsk.jpg	Animation, Adventure, Family	t
245	The Death of Robin Hood	A battle-worn Robin Hood grapples with his past and finds a chance at salvation.	Aaron Ryder, Andrew Swett, Alexander Black	2026-06-19	02:02:00	R	https://image.tmdb.org/t/p/w500/avPlzUHfIGuXecXohtOJiAlMXH8.jpg	Adventure, Drama, Thriller	t
246	Supergirl	A jaded Kara Zor-El embarks on a galactic journey to help a young alien girl seek revenge.	James Gunn, Peter Safran	2026-06-26	02:10:00	PG-13	https://cdn.moviefone.com/admin-uploads/highlights/images/supergirl-official-poster_1765397770.webp	Sci-Fi, Fantasy, Superhero	t
247	Moana (Live-Action)	A young woman sets sail on a daring mission to save her people.	Dwayne Johnson	2026-07-10	02:00:00	PG	https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg	Adventure, Fantasy, Family	t
248	Evil Dead Burn	A gathering at a secluded family home descends into a Deadite-infested nightmare.	Sam Raimi, Rob Tapert	2026-07-10	01:30:00	R	https://cdn.moviefone.com/admin-uploads/highlights/images/evil-dead-burn-official-poster_1778002073.webp	Horror, Thriller	t
249	Spider-Man: Brand New Day	Peter Parker's life is reset after the events of No Way Home.	Kevin Feige	2026-07-31	02:20:00	PG-13	https://image.tmdb.org/t/p/w500/ucQ0QBXXQPSxeUmWfh4YQenIuB9.jpg	Action, Adventure, Sci-Fi	t
\.


--
-- Data for Name: screenings_purchase; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.screenings_purchase (id, status, created_at, paid_at, cancelled_at, total_price, client_id) FROM stdin;
37	PAID	2026-06-26 02:12:05.134134+00	2026-06-26 02:12:05.134134+00	\N	30.00	38
38	PAID	2026-06-21 00:39:05.83796+00	2026-06-21 00:39:05.83796+00	\N	37.50	38
17	PAID	2026-06-23 16:46:50.765525+00	2026-06-23 16:46:50.765525+00	\N	15.00	29
18	PAID	2026-06-24 08:42:51.114668+00	2026-06-24 08:42:51.114668+00	\N	22.50	29
19	PAID	2026-06-23 01:20:51.460409+00	2026-06-23 01:20:51.460409+00	\N	20.00	30
20	PAID	2026-06-21 16:54:52.143516+00	2026-06-21 16:54:52.143516+00	\N	30.00	30
21	PAID	2026-06-24 22:33:52.833532+00	2026-06-24 22:33:52.833532+00	\N	25.00	30
22	PAID	2026-06-21 01:48:53.519833+00	2026-06-21 01:48:53.519833+00	\N	42.50	31
23	PAID	2026-06-24 14:52:54.542445+00	2026-06-24 14:52:54.542445+00	\N	20.00	31
24	PAID	2026-06-22 12:41:55.226575+00	2026-06-22 12:41:55.226575+00	\N	25.00	32
25	PAID	2026-06-19 18:47:55.919367+00	2026-06-19 18:47:55.919367+00	\N	30.00	32
26	PAID	2026-06-21 09:39:56.946593+00	2026-06-21 09:39:56.946593+00	\N	10.00	32
27	PAID	2026-06-19 18:18:57.290381+00	2026-06-19 18:18:57.290381+00	\N	55.00	33
28	PAID	2026-06-22 06:59:58.321888+00	2026-06-22 06:59:58.321888+00	\N	45.00	33
29	PAID	2026-06-19 15:21:59.013089+00	2026-06-19 15:21:59.013089+00	\N	10.00	33
30	PAID	2026-06-22 05:10:59.354939+00	2026-06-22 05:10:59.354939+00	\N	25.00	33
31	PAID	2026-06-21 01:40:00.035083+00	2026-06-21 01:40:00.035083+00	\N	20.00	34
32	PAID	2026-06-26 08:10:00.719752+00	2026-06-26 08:10:00.719752+00	\N	47.50	35
33	PAID	2026-06-23 08:26:01.735167+00	2026-06-23 08:26:01.735167+00	\N	35.00	36
34	PAID	2026-06-20 10:32:02.749321+00	2026-06-20 10:32:02.749321+00	\N	40.00	36
35	PAID	2026-06-23 03:01:03.76798+00	2026-06-23 03:01:03.76798+00	\N	30.00	37
36	PAID	2026-06-26 03:35:04.784443+00	2026-06-26 03:35:04.784443+00	\N	22.50	37
\.


--
-- Data for Name: screenings_screening; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.screenings_screening (id, start_time, base_price, hall_id, movie_id) FROM stdin;
1544	2026-06-26 10:00:00+00	15.00	1	245
1545	2026-06-26 13:30:00+00	15.00	1	241
1546	2026-06-26 17:00:00+00	15.00	1	239
1547	2026-06-26 20:30:00+00	15.00	1	234
1548	2026-06-26 10:00:00+00	10.00	2	245
1549	2026-06-26 13:30:00+00	10.00	2	245
1550	2026-06-26 17:00:00+00	10.00	2	243
1551	2026-06-26 20:30:00+00	10.00	2	233
1552	2026-06-26 10:00:00+00	10.00	3	242
1553	2026-06-26 13:30:00+00	10.00	3	241
1554	2026-06-26 17:00:00+00	10.00	3	240
1555	2026-06-26 20:30:00+00	10.00	3	236
1556	2026-06-26 10:00:00+00	15.00	4	241
1557	2026-06-26 13:30:00+00	15.00	4	243
1558	2026-06-26 17:00:00+00	15.00	4	235
1560	2026-06-26 10:00:00+00	10.00	5	238
1561	2026-06-26 13:30:00+00	10.00	5	241
1562	2026-06-26 17:00:00+00	10.00	5	235
1563	2026-06-26 20:30:00+00	10.00	5	246
1564	2026-06-27 10:00:00+00	15.00	1	239
1566	2026-06-27 17:00:00+00	15.00	1	242
1567	2026-06-27 20:30:00+00	15.00	1	238
1568	2026-06-27 10:00:00+00	10.00	2	246
1569	2026-06-27 13:30:00+00	10.00	2	235
1571	2026-06-27 20:30:00+00	10.00	2	241
1573	2026-06-27 13:30:00+00	10.00	3	239
1574	2026-06-27 17:00:00+00	10.00	3	234
1575	2026-06-27 20:30:00+00	10.00	3	243
1576	2026-06-27 10:00:00+00	15.00	4	242
1578	2026-06-27 17:00:00+00	15.00	4	244
1579	2026-06-27 20:30:00+00	15.00	4	235
1580	2026-06-27 10:00:00+00	10.00	5	245
1582	2026-06-27 17:00:00+00	10.00	5	239
1583	2026-06-27 20:30:00+00	10.00	5	246
1584	2026-06-28 10:00:00+00	15.00	1	238
1585	2026-06-28 13:30:00+00	15.00	1	236
1586	2026-06-28 17:00:00+00	15.00	1	234
1587	2026-06-28 20:30:00+00	15.00	1	246
1588	2026-06-28 10:00:00+00	10.00	2	231
1589	2026-06-28 13:30:00+00	10.00	2	242
1590	2026-06-28 17:00:00+00	10.00	2	233
1591	2026-06-28 20:30:00+00	10.00	2	244
1592	2026-06-28 10:00:00+00	10.00	3	234
1593	2026-06-28 13:30:00+00	10.00	3	241
1595	2026-06-28 20:30:00+00	10.00	3	241
1596	2026-06-28 10:00:00+00	15.00	4	238
1598	2026-06-28 17:00:00+00	15.00	4	246
1600	2026-06-28 10:00:00+00	10.00	5	243
1601	2026-06-28 13:30:00+00	10.00	5	244
1603	2026-06-28 20:30:00+00	10.00	5	236
1604	2026-06-29 10:00:00+00	15.00	1	243
1605	2026-06-29 13:30:00+00	15.00	1	244
1607	2026-06-29 20:30:00+00	15.00	1	236
1608	2026-06-29 10:00:00+00	10.00	2	240
1609	2026-06-29 13:30:00+00	10.00	2	240
1610	2026-06-29 17:00:00+00	10.00	2	231
1611	2026-06-29 20:30:00+00	10.00	2	246
1612	2026-06-29 10:00:00+00	10.00	3	243
1613	2026-06-29 13:30:00+00	10.00	3	243
1614	2026-06-29 17:00:00+00	10.00	3	239
1615	2026-06-29 20:30:00+00	10.00	3	235
1616	2026-06-29 10:00:00+00	15.00	4	231
1617	2026-06-29 13:30:00+00	15.00	4	245
1618	2026-06-29 17:00:00+00	15.00	4	235
1619	2026-06-29 20:30:00+00	15.00	4	240
1620	2026-06-29 10:00:00+00	10.00	5	245
1621	2026-06-29 13:30:00+00	10.00	5	242
1622	2026-06-29 17:00:00+00	10.00	5	245
1623	2026-06-29 20:30:00+00	10.00	5	239
1624	2026-06-30 10:00:00+00	15.00	1	238
1625	2026-06-30 13:30:00+00	15.00	1	239
1626	2026-06-30 17:00:00+00	15.00	1	231
1627	2026-06-30 20:30:00+00	15.00	1	241
1628	2026-06-30 10:00:00+00	10.00	2	234
1629	2026-06-30 13:30:00+00	10.00	2	238
1630	2026-06-30 17:00:00+00	10.00	2	239
1631	2026-06-30 20:30:00+00	10.00	2	246
1632	2026-06-30 10:00:00+00	10.00	3	236
1633	2026-06-30 13:30:00+00	10.00	3	232
1634	2026-06-30 17:00:00+00	10.00	3	235
1635	2026-06-30 20:30:00+00	10.00	3	238
1636	2026-06-30 10:00:00+00	15.00	4	242
1637	2026-06-30 13:30:00+00	15.00	4	241
1638	2026-06-30 17:00:00+00	15.00	4	234
1639	2026-06-30 20:30:00+00	15.00	4	232
1640	2026-06-30 10:00:00+00	10.00	5	236
1641	2026-06-30 13:30:00+00	10.00	5	246
1642	2026-06-30 17:00:00+00	10.00	5	244
1643	2026-06-30 20:30:00+00	10.00	5	236
1644	2026-07-01 10:00:00+00	15.00	1	235
1645	2026-07-01 13:30:00+00	15.00	1	241
1646	2026-07-01 17:00:00+00	15.00	1	245
1647	2026-07-01 20:30:00+00	15.00	1	239
1648	2026-07-01 10:00:00+00	10.00	2	235
1649	2026-07-01 13:30:00+00	10.00	2	241
1650	2026-07-01 17:00:00+00	10.00	2	241
1651	2026-07-01 20:30:00+00	10.00	2	245
1652	2026-07-01 10:00:00+00	10.00	3	245
1653	2026-07-01 13:30:00+00	10.00	3	244
1654	2026-07-01 17:00:00+00	10.00	3	242
1655	2026-07-01 20:30:00+00	10.00	3	238
1656	2026-07-01 10:00:00+00	15.00	4	235
1659	2026-07-01 20:30:00+00	15.00	4	242
1660	2026-07-01 10:00:00+00	10.00	5	246
1661	2026-07-01 13:30:00+00	10.00	5	242
1662	2026-07-01 17:00:00+00	10.00	5	234
1664	2026-07-02 10:00:00+00	15.00	1	244
1665	2026-07-02 13:30:00+00	15.00	1	241
1666	2026-07-02 17:00:00+00	15.00	1	239
1668	2026-07-02 10:00:00+00	10.00	2	239
1669	2026-07-02 13:30:00+00	10.00	2	235
1670	2026-07-02 17:00:00+00	10.00	2	233
1671	2026-07-02 20:30:00+00	10.00	2	232
1672	2026-07-02 10:00:00+00	10.00	3	239
1673	2026-07-02 13:30:00+00	10.00	3	231
1674	2026-07-02 17:00:00+00	10.00	3	243
1675	2026-07-02 20:30:00+00	10.00	3	236
1676	2026-07-02 10:00:00+00	15.00	4	238
1677	2026-07-02 13:30:00+00	15.00	4	243
1678	2026-07-02 17:00:00+00	15.00	4	244
1679	2026-07-02 20:30:00+00	15.00	4	240
1680	2026-07-02 10:00:00+00	10.00	5	241
1681	2026-07-02 13:30:00+00	10.00	5	242
1682	2026-07-02 17:00:00+00	10.00	5	233
1683	2026-07-02 20:30:00+00	10.00	5	232
\.


--
-- Data for Name: screenings_seat; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.screenings_seat (id, row_label, seat_number, grid_x, grid_y, seat_type, hall_id) FROM stdin;
1	A	1	1	1	REGULAR	1
2	A	2	2	1	REGULAR	1
3	A	3	3	1	REGULAR	1
4	A	4	4	1	REGULAR	1
5	A	5	5	1	REGULAR	1
6	A	6	6	1	REGULAR	1
7	A	7	7	1	REGULAR	1
8	A	8	8	1	REGULAR	1
9	A	9	9	1	REGULAR	1
10	A	10	10	1	REGULAR	1
11	A	11	11	1	REGULAR	1
12	A	12	12	1	REGULAR	1
13	A	13	13	1	REGULAR	1
14	A	14	14	1	REGULAR	1
15	A	15	15	1	REGULAR	1
16	A	16	16	1	REGULAR	1
17	B	1	1	2	REGULAR	1
18	B	2	2	2	REGULAR	1
19	B	3	3	2	REGULAR	1
20	B	4	4	2	REGULAR	1
21	B	5	5	2	REGULAR	1
22	B	6	6	2	REGULAR	1
23	B	7	7	2	REGULAR	1
24	B	8	8	2	REGULAR	1
25	B	9	9	2	REGULAR	1
26	B	10	10	2	REGULAR	1
27	B	11	11	2	REGULAR	1
28	B	12	12	2	REGULAR	1
29	B	13	13	2	REGULAR	1
30	B	14	14	2	REGULAR	1
31	B	15	15	2	REGULAR	1
32	B	16	16	2	REGULAR	1
33	C	1	1	3	REGULAR	1
34	C	2	2	3	REGULAR	1
35	C	3	3	3	REGULAR	1
36	C	4	4	3	REGULAR	1
37	C	5	5	3	REGULAR	1
38	C	6	6	3	REGULAR	1
39	C	7	7	3	REGULAR	1
40	C	8	8	3	REGULAR	1
41	C	9	9	3	REGULAR	1
42	C	10	10	3	REGULAR	1
43	C	11	11	3	REGULAR	1
44	C	12	12	3	REGULAR	1
45	C	13	13	3	REGULAR	1
46	C	14	14	3	REGULAR	1
47	C	15	15	3	REGULAR	1
48	C	16	16	3	REGULAR	1
49	D	1	1	4	REGULAR	1
50	D	2	2	4	REGULAR	1
51	D	3	3	4	REGULAR	1
52	D	4	4	4	REGULAR	1
53	D	5	5	4	REGULAR	1
54	D	6	6	4	REGULAR	1
55	D	7	7	4	REGULAR	1
56	D	8	8	4	REGULAR	1
57	D	9	9	4	REGULAR	1
58	D	10	10	4	REGULAR	1
59	D	11	11	4	REGULAR	1
60	D	12	12	4	REGULAR	1
61	D	13	13	4	REGULAR	1
62	D	14	14	4	REGULAR	1
63	D	15	15	4	REGULAR	1
64	D	16	16	4	REGULAR	1
65	E	1	1	5	REGULAR	1
66	E	2	2	5	REGULAR	1
67	E	3	3	5	REGULAR	1
68	E	4	4	5	REGULAR	1
69	E	5	5	5	REGULAR	1
70	E	6	6	5	REGULAR	1
71	E	7	7	5	REGULAR	1
72	E	8	8	5	REGULAR	1
73	E	9	9	5	REGULAR	1
74	E	10	10	5	REGULAR	1
75	E	11	11	5	REGULAR	1
76	E	12	12	5	REGULAR	1
77	E	13	13	5	REGULAR	1
78	E	14	14	5	REGULAR	1
79	E	15	15	5	REGULAR	1
80	E	16	16	5	REGULAR	1
81	F	1	1	6	REGULAR	1
82	F	2	2	6	REGULAR	1
83	F	3	3	6	REGULAR	1
84	F	4	4	6	REGULAR	1
85	F	5	5	6	REGULAR	1
86	F	6	6	6	REGULAR	1
87	F	7	7	6	REGULAR	1
88	F	8	8	6	REGULAR	1
89	F	9	9	6	REGULAR	1
90	F	10	10	6	REGULAR	1
91	F	11	11	6	REGULAR	1
92	F	12	12	6	REGULAR	1
93	F	13	13	6	REGULAR	1
94	F	14	14	6	REGULAR	1
95	F	15	15	6	REGULAR	1
96	F	16	16	6	REGULAR	1
97	G	1	1	7	REGULAR	1
98	G	2	2	7	REGULAR	1
99	G	3	3	7	REGULAR	1
100	G	4	4	7	REGULAR	1
101	G	5	5	7	REGULAR	1
102	G	6	6	7	REGULAR	1
103	G	7	7	7	REGULAR	1
104	G	8	8	7	REGULAR	1
105	G	9	9	7	REGULAR	1
106	G	10	10	7	REGULAR	1
107	G	11	11	7	REGULAR	1
108	G	12	12	7	REGULAR	1
109	G	13	13	7	REGULAR	1
110	G	14	14	7	REGULAR	1
111	G	15	15	7	REGULAR	1
112	G	16	16	7	REGULAR	1
113	H	1	1	8	REGULAR	1
114	H	2	2	8	REGULAR	1
115	H	3	3	8	REGULAR	1
116	H	4	4	8	REGULAR	1
117	H	5	5	8	REGULAR	1
118	H	6	6	8	REGULAR	1
119	H	7	7	8	REGULAR	1
120	H	8	8	8	REGULAR	1
121	H	9	9	8	REGULAR	1
122	H	10	10	8	REGULAR	1
123	H	11	11	8	REGULAR	1
124	H	12	12	8	REGULAR	1
125	H	13	13	8	REGULAR	1
126	H	14	14	8	REGULAR	1
127	H	15	15	8	REGULAR	1
128	H	16	16	8	REGULAR	1
129	I	1	1	9	REGULAR	1
130	I	2	2	9	REGULAR	1
131	I	3	3	9	REGULAR	1
132	I	4	4	9	REGULAR	1
133	I	5	5	9	REGULAR	1
134	I	6	6	9	REGULAR	1
135	I	7	7	9	REGULAR	1
136	I	8	8	9	REGULAR	1
137	I	9	9	9	REGULAR	1
138	I	10	10	9	REGULAR	1
139	I	11	11	9	REGULAR	1
140	I	12	12	9	REGULAR	1
141	I	13	13	9	REGULAR	1
142	I	14	14	9	REGULAR	1
143	I	15	15	9	REGULAR	1
144	I	16	16	9	REGULAR	1
145	J	1	1	10	REGULAR	1
146	J	2	2	10	REGULAR	1
147	J	3	3	10	REGULAR	1
148	J	4	4	10	REGULAR	1
150	J	6	6	10	REGULAR	1
151	J	7	7	10	REGULAR	1
152	J	8	8	10	REGULAR	1
153	J	9	9	10	REGULAR	1
154	J	10	10	10	REGULAR	1
155	J	11	11	10	REGULAR	1
156	J	12	12	10	REGULAR	1
157	J	13	13	10	REGULAR	1
158	J	14	14	10	REGULAR	1
159	J	15	15	10	REGULAR	1
160	J	16	16	10	REGULAR	1
161	K	1	1	11	VIP	1
162	K	2	2	11	VIP	1
163	K	3	3	11	VIP	1
164	K	4	4	11	VIP	1
165	K	5	5	11	VIP	1
166	K	6	6	11	VIP	1
167	K	7	7	11	VIP	1
168	K	8	8	11	VIP	1
169	K	9	9	11	VIP	1
170	K	10	10	11	VIP	1
171	K	11	11	11	VIP	1
172	K	12	12	11	VIP	1
173	K	13	13	11	VIP	1
174	K	14	14	11	VIP	1
175	K	15	15	11	VIP	1
176	K	16	16	11	VIP	1
177	L	1	1	12	VIP	1
178	L	2	2	12	VIP	1
179	L	3	3	12	VIP	1
180	L	4	4	12	VIP	1
181	L	5	5	12	VIP	1
182	L	6	6	12	VIP	1
183	L	7	7	12	VIP	1
184	L	8	8	12	VIP	1
185	L	9	9	12	VIP	1
186	L	10	10	12	VIP	1
187	L	11	11	12	VIP	1
188	L	12	12	12	VIP	1
189	L	13	13	12	VIP	1
190	L	14	14	12	VIP	1
191	L	15	15	12	VIP	1
192	L	16	16	12	VIP	1
193	A	1	1	1	REGULAR	2
194	A	2	2	1	REGULAR	2
195	A	3	3	1	REGULAR	2
196	A	4	4	1	REGULAR	2
197	A	5	5	1	REGULAR	2
198	A	6	6	1	REGULAR	2
199	A	7	7	1	REGULAR	2
200	A	8	8	1	REGULAR	2
201	A	9	9	1	REGULAR	2
202	A	10	10	1	REGULAR	2
203	A	11	11	1	REGULAR	2
204	A	12	12	1	REGULAR	2
205	B	1	1	2	REGULAR	2
206	B	2	2	2	REGULAR	2
207	B	3	3	2	REGULAR	2
208	B	4	4	2	REGULAR	2
209	B	5	5	2	REGULAR	2
210	B	6	6	2	REGULAR	2
211	B	7	7	2	REGULAR	2
212	B	8	8	2	REGULAR	2
213	B	9	9	2	REGULAR	2
214	B	10	10	2	REGULAR	2
215	B	11	11	2	REGULAR	2
216	B	12	12	2	REGULAR	2
217	C	1	1	3	REGULAR	2
218	C	2	2	3	REGULAR	2
219	C	3	3	3	REGULAR	2
220	C	4	4	3	REGULAR	2
221	C	5	5	3	REGULAR	2
222	C	6	6	3	REGULAR	2
223	C	7	7	3	REGULAR	2
224	C	8	8	3	REGULAR	2
225	C	9	9	3	REGULAR	2
226	C	10	10	3	REGULAR	2
227	C	11	11	3	REGULAR	2
228	C	12	12	3	REGULAR	2
229	D	1	1	4	REGULAR	2
230	D	2	2	4	REGULAR	2
231	D	3	3	4	REGULAR	2
232	D	4	4	4	REGULAR	2
233	D	5	5	4	REGULAR	2
234	D	6	6	4	REGULAR	2
235	D	7	7	4	REGULAR	2
236	D	8	8	4	REGULAR	2
237	D	9	9	4	REGULAR	2
238	D	10	10	4	REGULAR	2
239	D	11	11	4	REGULAR	2
240	D	12	12	4	REGULAR	2
241	E	1	1	5	REGULAR	2
242	E	2	2	5	REGULAR	2
243	E	3	3	5	REGULAR	2
244	E	4	4	5	REGULAR	2
245	E	5	5	5	REGULAR	2
246	E	6	6	5	REGULAR	2
247	E	7	7	5	REGULAR	2
248	E	8	8	5	REGULAR	2
249	E	9	9	5	REGULAR	2
250	E	10	10	5	REGULAR	2
251	E	11	11	5	REGULAR	2
252	E	12	12	5	REGULAR	2
253	F	1	1	6	REGULAR	2
254	F	2	2	6	REGULAR	2
255	F	3	3	6	REGULAR	2
256	F	4	4	6	REGULAR	2
257	F	5	5	6	REGULAR	2
258	F	6	6	6	REGULAR	2
259	F	7	7	6	REGULAR	2
260	F	8	8	6	REGULAR	2
261	F	9	9	6	REGULAR	2
262	F	10	10	6	REGULAR	2
263	F	11	11	6	REGULAR	2
264	F	12	12	6	REGULAR	2
265	G	1	1	7	VIP	2
266	G	2	2	7	VIP	2
267	G	3	3	7	VIP	2
268	G	4	4	7	VIP	2
269	G	5	5	7	VIP	2
270	G	6	6	7	VIP	2
271	G	7	7	7	VIP	2
272	G	8	8	7	VIP	2
273	G	9	9	7	VIP	2
274	G	10	10	7	VIP	2
275	G	11	11	7	VIP	2
276	G	12	12	7	VIP	2
277	H	1	1	8	VIP	2
278	H	2	2	8	VIP	2
279	H	3	3	8	VIP	2
280	H	4	4	8	VIP	2
281	H	5	5	8	VIP	2
282	H	6	6	8	VIP	2
283	H	7	7	8	VIP	2
284	H	8	8	8	VIP	2
285	H	9	9	8	VIP	2
286	H	10	10	8	VIP	2
287	H	11	11	8	VIP	2
288	H	12	12	8	VIP	2
289	A	1	1	1	REGULAR	3
290	A	2	2	1	REGULAR	3
291	A	3	3	1	REGULAR	3
292	A	4	4	1	REGULAR	3
293	A	5	5	1	REGULAR	3
294	A	6	6	1	REGULAR	3
295	A	7	7	1	REGULAR	3
296	A	8	8	1	REGULAR	3
297	A	9	9	1	REGULAR	3
298	A	10	10	1	REGULAR	3
299	A	11	11	1	REGULAR	3
300	A	12	12	1	REGULAR	3
301	B	1	1	2	REGULAR	3
302	B	2	2	2	REGULAR	3
303	B	3	3	2	REGULAR	3
304	B	4	4	2	REGULAR	3
305	B	5	5	2	REGULAR	3
306	B	6	6	2	REGULAR	3
307	B	7	7	2	REGULAR	3
308	B	8	8	2	REGULAR	3
309	B	9	9	2	REGULAR	3
310	B	10	10	2	REGULAR	3
311	B	11	11	2	REGULAR	3
312	B	12	12	2	REGULAR	3
313	C	1	1	3	REGULAR	3
314	C	2	2	3	REGULAR	3
315	C	3	3	3	REGULAR	3
316	C	4	4	3	REGULAR	3
317	C	5	5	3	REGULAR	3
318	C	6	6	3	REGULAR	3
319	C	7	7	3	REGULAR	3
320	C	8	8	3	REGULAR	3
321	C	9	9	3	REGULAR	3
322	C	10	10	3	REGULAR	3
323	C	11	11	3	REGULAR	3
324	C	12	12	3	REGULAR	3
325	D	1	1	4	REGULAR	3
326	D	2	2	4	REGULAR	3
327	D	3	3	4	REGULAR	3
328	D	4	4	4	REGULAR	3
329	D	5	5	4	REGULAR	3
330	D	6	6	4	REGULAR	3
331	D	7	7	4	REGULAR	3
332	D	8	8	4	REGULAR	3
333	D	9	9	4	REGULAR	3
334	D	10	10	4	REGULAR	3
335	D	11	11	4	REGULAR	3
336	D	12	12	4	REGULAR	3
337	E	1	1	5	REGULAR	3
338	E	2	2	5	REGULAR	3
339	E	3	3	5	REGULAR	3
340	E	4	4	5	REGULAR	3
341	E	5	5	5	REGULAR	3
342	E	6	6	5	REGULAR	3
343	E	7	7	5	REGULAR	3
344	E	8	8	5	REGULAR	3
345	E	9	9	5	REGULAR	3
346	E	10	10	5	REGULAR	3
347	E	11	11	5	REGULAR	3
348	E	12	12	5	REGULAR	3
349	F	1	1	6	REGULAR	3
350	F	2	2	6	REGULAR	3
351	F	3	3	6	REGULAR	3
352	F	4	4	6	REGULAR	3
353	F	5	5	6	REGULAR	3
354	F	6	6	6	REGULAR	3
355	F	7	7	6	REGULAR	3
356	F	8	8	6	REGULAR	3
357	F	9	9	6	REGULAR	3
358	F	10	10	6	REGULAR	3
359	F	11	11	6	REGULAR	3
360	F	12	12	6	REGULAR	3
361	G	1	1	7	VIP	3
362	G	2	2	7	VIP	3
363	G	3	3	7	VIP	3
364	G	4	4	7	VIP	3
365	G	5	5	7	VIP	3
366	G	6	6	7	VIP	3
367	G	7	7	7	VIP	3
368	G	8	8	7	VIP	3
369	G	9	9	7	VIP	3
370	G	10	10	7	VIP	3
371	G	11	11	7	VIP	3
372	G	12	12	7	VIP	3
373	H	1	1	8	VIP	3
374	H	2	2	8	VIP	3
375	H	3	3	8	VIP	3
376	H	4	4	8	VIP	3
377	H	5	5	8	VIP	3
378	H	6	6	8	VIP	3
379	H	7	7	8	VIP	3
380	H	8	8	8	VIP	3
381	H	9	9	8	VIP	3
382	H	10	10	8	VIP	3
383	H	11	11	8	VIP	3
384	H	12	12	8	VIP	3
385	A	1	1	1	VIP	4
386	A	2	2	1	VIP	4
387	A	3	3	1	VIP	4
388	A	4	4	1	VIP	4
389	A	5	5	1	VIP	4
390	A	6	6	1	VIP	4
391	B	1	1	2	VIP	4
392	B	2	2	2	VIP	4
393	B	3	3	2	VIP	4
394	B	4	4	2	VIP	4
395	B	5	5	2	VIP	4
396	B	6	6	2	VIP	4
397	C	1	1	3	VIP	4
398	C	2	2	3	VIP	4
399	C	3	3	3	VIP	4
400	C	4	4	3	VIP	4
401	C	5	5	3	VIP	4
402	C	6	6	3	VIP	4
403	D	1	1	4	VIP	4
404	D	2	2	4	VIP	4
405	D	3	3	4	VIP	4
406	D	4	4	4	VIP	4
407	D	5	5	4	VIP	4
408	D	6	6	4	VIP	4
409	A	1	1	1	REGULAR	5
410	A	2	2	1	REGULAR	5
411	A	3	3	1	REGULAR	5
412	A	4	4	1	REGULAR	5
413	A	5	5	1	REGULAR	5
414	A	6	6	1	REGULAR	5
415	A	7	7	1	REGULAR	5
416	A	8	8	1	REGULAR	5
417	A	9	9	1	REGULAR	5
418	A	10	10	1	REGULAR	5
419	B	1	1	2	REGULAR	5
420	B	2	2	2	REGULAR	5
421	B	3	3	2	REGULAR	5
422	B	4	4	2	REGULAR	5
423	B	5	5	2	REGULAR	5
424	B	6	6	2	REGULAR	5
425	B	7	7	2	REGULAR	5
426	B	8	8	2	REGULAR	5
427	B	9	9	2	REGULAR	5
428	B	10	10	2	REGULAR	5
429	C	1	1	3	REGULAR	5
430	C	2	2	3	REGULAR	5
431	C	3	3	3	REGULAR	5
432	C	4	4	3	REGULAR	5
433	C	5	5	3	REGULAR	5
434	C	6	6	3	REGULAR	5
435	C	7	7	3	REGULAR	5
436	C	8	8	3	REGULAR	5
437	C	9	9	3	REGULAR	5
438	C	10	10	3	REGULAR	5
439	D	1	1	4	REGULAR	5
440	D	2	2	4	REGULAR	5
441	D	3	3	4	REGULAR	5
442	D	4	4	4	REGULAR	5
443	D	5	5	4	REGULAR	5
444	D	6	6	4	REGULAR	5
445	D	7	7	4	REGULAR	5
446	D	8	8	4	REGULAR	5
447	D	9	9	4	REGULAR	5
448	D	10	10	4	REGULAR	5
449	E	1	1	5	VIP	5
450	E	2	2	5	VIP	5
451	E	3	3	5	VIP	5
452	E	4	4	5	VIP	5
453	E	5	5	5	VIP	5
454	E	6	6	5	VIP	5
455	E	7	7	5	VIP	5
456	E	8	8	5	VIP	5
457	E	9	9	5	VIP	5
458	E	10	10	5	VIP	5
459	F	1	1	6	VIP	5
460	F	2	2	6	VIP	5
461	F	3	3	6	VIP	5
462	F	4	4	6	VIP	5
463	F	5	5	6	VIP	5
464	F	6	6	6	VIP	5
465	F	7	7	6	VIP	5
466	F	8	8	6	VIP	5
467	F	9	9	6	VIP	5
468	F	10	10	6	VIP	5
149	J	5	5	10	REGULAR	1
\.


--
-- Data for Name: screenings_ticket; Type: TABLE DATA; Schema: public; Owner: cinema
--

COPY public.screenings_ticket (id, price_paid, created_at, client_id, screening_id, seat_id, salt, secret_hash, is_used, purchase_id) FROM stdin;
82	10.00	2026-06-26 14:17:57.280954+00	32	1600	444	nq1yG8fP	pbkdf2_sha256$600000$nq1yG8fP$gt7ESQUGTStMClRPRW5fc4HHDqh3qmZDWHMj0lVLAM0=	f	26
83	22.50	2026-06-26 14:17:57.636761+00	33	1638	398	5RFO2gOV	pbkdf2_sha256$600000$5RFO2gOV$yOsnynM0+/ug8b09oerrN0tULXA+Kqlr9aKS1zc6ZU0=	f	27
84	10.00	2026-06-26 14:17:57.977842+00	33	1603	429	HahmIwI7	pbkdf2_sha256$600000$HahmIwI7$BYzNYRqDDgE93FEgvWEeEp0caGpVv3z0lBCQ24VBM/Y=	f	27
86	22.50	2026-06-26 14:17:58.656972+00	33	1619	388	MfVSnnzV	pbkdf2_sha256$600000$MfVSnnzV$uyJ3PJXBopZ2GMBea2DGMw2jj8R50ieZTy33ZTy/T4U=	f	28
66	10.00	2026-06-26 14:17:51.796298+00	30	1551	243	PGTdkKN2	pbkdf2_sha256$600000$PGTdkKN2$LQ2hXGngSMWM1jBGsK+dzXyAiLG4xeKhQbz26RwOqHM=	f	19
67	10.00	2026-06-26 14:17:52.134834+00	30	1673	307	0ddQCVwg	pbkdf2_sha256$600000$0ddQCVwg$3NvZZu8rEEFLYXWD9yqbsitFTjh++7dJzfBM/iGBHS0=	f	19
68	15.00	2026-06-26 14:17:52.481508+00	30	1610	287	dAHWZuSg	pbkdf2_sha256$600000$dAHWZuSg$19NJMldQjQlblqBbPASi251p1mSVNS5f6PlceS8UYIc=	f	20
69	15.00	2026-06-26 14:17:52.824829+00	30	1644	93	b0u2ymyP	pbkdf2_sha256$600000$b0u2ymyP$CjTLMx1L6Kh5pq1Cw2VOwjFDih7rXF2szMYQACa4qfg=	f	20
70	15.00	2026-06-26 14:17:53.168392+00	30	1627	75	z8RCowMa	pbkdf2_sha256$600000$z8RCowMa$UpxYiNNTh6PDfE/WqfT0snTnGNAq4Z4i1iixwEuZfCg=	f	21
71	10.00	2026-06-26 14:17:53.51059+00	30	1582	409	DiFoOUkT	pbkdf2_sha256$600000$DiFoOUkT$x0brA2rgMDDDN2ynhAZmWmUlMEQih/7ba9qQLXqIg7M=	f	21
72	10.00	2026-06-26 14:17:53.856782+00	31	1672	314	ec4Qr5eD	pbkdf2_sha256$600000$ec4Qr5eD$nIIwdGY0H3AwzNAV5emp1GkQIrsS4dqFwua3cPe8BHw=	f	22
73	10.00	2026-06-26 14:17:54.19452+00	31	1549	237	78HAAnRw	pbkdf2_sha256$600000$78HAAnRw$KxgrLyTDV4gqAtFQliSDXppztGTKh8AeV17FhRlgu10=	f	22
74	22.50	2026-06-26 14:17:54.53364+00	31	1678	398	bLZXnNoK	pbkdf2_sha256$600000$bLZXnNoK$kvM7YcDURGNLgg0wYGPrfUcW2KxvFzxrESdaUJ6Q9U0=	f	22
75	10.00	2026-06-26 14:17:54.878119+00	31	1652	350	9gERcYVJ	pbkdf2_sha256$600000$9gERcYVJ$DpeREloYDVcUwhC6usygIXE+QxhmAy7Pe0Idr2aJbW0=	f	23
76	10.00	2026-06-26 14:17:55.217606+00	31	1552	353	1vNC759J	pbkdf2_sha256$600000$1vNC759J$e7CZqXPPqav9IvVaogJhIPJzUOOs0I/8BNJE3gntduA=	f	23
77	10.00	2026-06-26 14:17:55.56696+00	32	1553	305	9TTVNvCN	pbkdf2_sha256$600000$9TTVNvCN$qVAp7A1kzQ8sfw37zlZV7z3ozXqa0GUEXtV0TdZ0DE0=	f	24
78	15.00	2026-06-26 14:17:55.906545+00	32	1587	66	px8SLCl3	pbkdf2_sha256$600000$px8SLCl3$iNj03mvFCqwnZhRRPODU71CNSU0i2btfpujryCyZKrM=	f	24
79	10.00	2026-06-26 14:17:56.25882+00	32	1591	228	7sLEPR8P	pbkdf2_sha256$600000$7sLEPR8P$h8batCBzqZbtMInEDw5tqOwsdFWxBiZxz2ZRqNAA//o=	f	25
80	10.00	2026-06-26 14:17:56.5997+00	32	1548	196	YEJ1v2VD	pbkdf2_sha256$600000$YEJ1v2VD$5BJQlApGwj0UJlBaOwXOtt7heKwz+PyjHzhkTJrF5TY=	f	25
81	10.00	2026-06-26 14:17:56.937851+00	32	1651	193	NuaN6r8B	pbkdf2_sha256$600000$NuaN6r8B$eraATLYPYKHAKC7fGGmKVPdDRI1RJ0bbhp5NJEdEEOQ=	f	25
88	10.00	2026-06-26 14:17:59.346283+00	33	1643	429	OhmVsY9T	pbkdf2_sha256$600000$OhmVsY9T$HP4uQErIRP1lC5c6ABg/Yz7dgtbNl63UUn1qwMkWLWQ=	f	29
89	10.00	2026-06-26 14:17:59.688767+00	33	1641	424	owQviBgJ	pbkdf2_sha256$600000$owQviBgJ$xVAMW3yWLx1GU/F7DKFCC80IN/SkxU5cFk7K5KcrrJ0=	f	30
90	15.00	2026-06-26 14:18:00.025855+00	33	1666	21	Q9LTiuKQ	pbkdf2_sha256$600000$Q9LTiuKQ$7yrxzZjlu8+E69zjF4tOi2jmDJgCqlz5KyKZAG5aN/0=	f	30
91	10.00	2026-06-26 14:18:00.370151+00	34	1682	423	4UT1WdfW	pbkdf2_sha256$600000$4UT1WdfW$HYIIJAiQBD7SSNC7vxMOHqFU0cTeEPLh4WM5SVuzN+E=	f	31
92	10.00	2026-06-26 14:18:00.711083+00	34	1560	425	mGPaFqZg	pbkdf2_sha256$600000$mGPaFqZg$6MaAZyTlDwKeZUmg9arz63bgu6ivFva8cy2K10f89vM=	f	31
93	10.00	2026-06-26 14:18:01.052207+00	35	1600	441	NY8iSJfs	pbkdf2_sha256$600000$NY8iSJfs$YapDYvHhmKuoVopak0AQ6Gxzs5obcmsVLuXKG+4HUVM=	f	32
94	15.00	2026-06-26 14:18:01.387996+00	35	1671	265	zTyEeW1r	pbkdf2_sha256$600000$zTyEeW1r$OogykWNTFHoutWBPuwBCKXZ3pu9910PnyC/WqwVRH68=	f	32
96	10.00	2026-06-26 14:18:02.067607+00	36	1549	203	CWge3SSH	pbkdf2_sha256$600000$CWge3SSH$ZGhvtgIUVAl0KC2WfgBXe9JYNWkoChUom0xIgcmmV8s=	f	33
97	10.00	2026-06-26 14:18:02.403151+00	36	1628	264	5pw56GNQ	pbkdf2_sha256$600000$5pw56GNQ$3mmxcfqZIBD7hMBUepO5HRpgW39uJtU4Jt8w4gb9yKM=	f	33
98	15.00	2026-06-26 14:18:02.740586+00	36	1564	28	24tePbfS	pbkdf2_sha256$600000$24tePbfS$lu7eELGLHUQZlFapSHt812Tg92VFGnE5nVvHygtL3Ms=	f	33
99	15.00	2026-06-26 14:18:03.08789+00	36	1546	93	oXbZKrto	pbkdf2_sha256$600000$oXbZKrto$OJ27MYw2rJrlbpume2XtipIAlNkUvJUx1Fzh7DgBBDU=	f	34
100	15.00	2026-06-26 14:18:03.422463+00	36	1629	278	rF583YDd	pbkdf2_sha256$600000$rF583YDd$72QqacxtQwonkAsquaUtWsdZoAQPUV55bQktuwHtz6E=	f	34
101	10.00	2026-06-26 14:18:03.759285+00	36	1611	255	pakxMn1x	pbkdf2_sha256$600000$pakxMn1x$tYiCG7VC3WSrezAKU2k+vOUbDu+f2pdO6P7Vi4Di4Yk=	f	34
102	10.00	2026-06-26 14:18:04.100522+00	37	1571	253	KkfB9K9A	pbkdf2_sha256$600000$KkfB9K9A$fTMvEnwqFq8GGkcompifHJepVfCutwGx5RUIAKDqFow=	f	35
103	10.00	2026-06-26 14:18:04.437601+00	37	1568	221	6pzhMsqE	pbkdf2_sha256$600000$6pzhMsqE$nXG+phCim+hdyTYJwhSiNykViDfqE6tKYW8sNd4uKCU=	f	35
104	10.00	2026-06-26 14:18:04.775471+00	37	1633	309	noW5csTQ	pbkdf2_sha256$600000$noW5csTQ$Cig6907yBViPqnUMEgfomfbvmMAnRKAKcabWWFcAYxI=	f	35
106	15.00	2026-06-26 14:18:05.476713+00	38	1607	97	kIAmXc9E	pbkdf2_sha256$600000$kIAmXc9E$LYcBmmdw+G9q00K+UgwyUVtsZvWMJwJTc8uPG05lNz8=	f	37
107	15.00	2026-06-26 14:18:05.82799+00	38	1620	468	IhAt3giK	pbkdf2_sha256$600000$IhAt3giK$pl+eJK1jR3UtUsIN7Ajs5vxGEmf1G0IXNefil4F9fx0=	f	37
108	15.00	2026-06-26 14:18:06.181977+00	38	1623	454	9MYFHUIE	pbkdf2_sha256$600000$9MYFHUIE$VQeA6HkyjqjXhMH1vHNWImjtNp3GHfbQEZ8sN9M2BZw=	f	38
109	22.50	2026-06-26 14:18:06.52761+00	38	1576	385	uEWYeocE	pbkdf2_sha256$600000$uEWYeocE$5rWmuSjIQ0Zl+4bFcI7FQ4/ezY8LHMLOhy4IbbNXcB8=	f	38
\.


--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.account_emailaddress_id_seq', 3, true);


--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.account_emailconfirmation_id_seq', 1, false);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 14, true);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 38, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 2, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 37, true);


--
-- Name: django_site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.django_site_id_seq', 1, true);


--
-- Name: screenings_hall_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.screenings_hall_id_seq', 11, true);


--
-- Name: screenings_movie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.screenings_movie_id_seq', 249, true);


--
-- Name: screenings_purchase_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.screenings_purchase_id_seq', 38, true);


--
-- Name: screenings_screening_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.screenings_screening_id_seq', 1683, true);


--
-- Name: screenings_seat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.screenings_seat_id_seq', 474, true);


--
-- Name: screenings_ticket_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cinema
--

SELECT pg_catalog.setval('public.screenings_ticket_id_seq', 109, true);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: screenings_hall screenings_hall_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_hall
    ADD CONSTRAINT screenings_hall_pkey PRIMARY KEY (id);


--
-- Name: screenings_movie screenings_movie_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_movie
    ADD CONSTRAINT screenings_movie_pkey PRIMARY KEY (id);


--
-- Name: screenings_purchase screenings_purchase_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_purchase
    ADD CONSTRAINT screenings_purchase_pkey PRIMARY KEY (id);


--
-- Name: screenings_screening screenings_screening_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_screening
    ADD CONSTRAINT screenings_screening_pkey PRIMARY KEY (id);


--
-- Name: screenings_seat screenings_seat_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_seat
    ADD CONSTRAINT screenings_seat_pkey PRIMARY KEY (id);


--
-- Name: screenings_ticket screenings_ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_ticket
    ADD CONSTRAINT screenings_ticket_pkey PRIMARY KEY (id);


--
-- Name: screenings_seat unique_seat_per_hall; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_seat
    ADD CONSTRAINT unique_seat_per_hall UNIQUE (hall_id, row_label, seat_number);


--
-- Name: screenings_ticket unique_ticket_per_screening; Type: CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_ticket
    ADD CONSTRAINT unique_ticket_per_screening UNIQUE (screening_id, seat_id);


--
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX account_emailaddress_email_03be32b2 ON public.account_emailaddress USING btree (email);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: screenings_purchase_client_id_057ed7b5; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX screenings_purchase_client_id_057ed7b5 ON public.screenings_purchase USING btree (client_id);


--
-- Name: screenings_screening_hall_id_c139c471; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX screenings_screening_hall_id_c139c471 ON public.screenings_screening USING btree (hall_id);


--
-- Name: screenings_screening_movie_id_dfe86e0e; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX screenings_screening_movie_id_dfe86e0e ON public.screenings_screening USING btree (movie_id);


--
-- Name: screenings_seat_hall_id_9477c508; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX screenings_seat_hall_id_9477c508 ON public.screenings_seat USING btree (hall_id);


--
-- Name: screenings_ticket_client_id_43964d3b; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX screenings_ticket_client_id_43964d3b ON public.screenings_ticket USING btree (client_id);


--
-- Name: screenings_ticket_purchase_id_585ce8e6; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX screenings_ticket_purchase_id_585ce8e6 ON public.screenings_ticket USING btree (purchase_id);


--
-- Name: screenings_ticket_screening_id_32ff694f; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX screenings_ticket_screening_id_32ff694f ON public.screenings_ticket USING btree (screening_id);


--
-- Name: screenings_ticket_seat_id_104b595d; Type: INDEX; Schema: public; Owner: cinema
--

CREATE INDEX screenings_ticket_seat_id_104b595d ON public.screenings_ticket USING btree (seat_id);


--
-- Name: unique_primary_email; Type: INDEX; Schema: public; Owner: cinema
--

CREATE UNIQUE INDEX unique_primary_email ON public.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- Name: unique_verified_email; Type: INDEX; Schema: public; Owner: cinema
--

CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: screenings_purchase screenings_purchase_client_id_057ed7b5_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_purchase
    ADD CONSTRAINT screenings_purchase_client_id_057ed7b5_fk_accounts_user_id FOREIGN KEY (client_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: screenings_screening screenings_screening_hall_id_c139c471_fk_screenings_hall_id; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_screening
    ADD CONSTRAINT screenings_screening_hall_id_c139c471_fk_screenings_hall_id FOREIGN KEY (hall_id) REFERENCES public.screenings_hall(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: screenings_screening screenings_screening_movie_id_dfe86e0e_fk_screenings_movie_id; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_screening
    ADD CONSTRAINT screenings_screening_movie_id_dfe86e0e_fk_screenings_movie_id FOREIGN KEY (movie_id) REFERENCES public.screenings_movie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: screenings_seat screenings_seat_hall_id_9477c508_fk_screenings_hall_id; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_seat
    ADD CONSTRAINT screenings_seat_hall_id_9477c508_fk_screenings_hall_id FOREIGN KEY (hall_id) REFERENCES public.screenings_hall(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: screenings_ticket screenings_ticket_client_id_43964d3b_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_ticket
    ADD CONSTRAINT screenings_ticket_client_id_43964d3b_fk_accounts_user_id FOREIGN KEY (client_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: screenings_ticket screenings_ticket_purchase_id_585ce8e6_fk_screening; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_ticket
    ADD CONSTRAINT screenings_ticket_purchase_id_585ce8e6_fk_screening FOREIGN KEY (purchase_id) REFERENCES public.screenings_purchase(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: screenings_ticket screenings_ticket_screening_id_32ff694f_fk_screening; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_ticket
    ADD CONSTRAINT screenings_ticket_screening_id_32ff694f_fk_screening FOREIGN KEY (screening_id) REFERENCES public.screenings_screening(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: screenings_ticket screenings_ticket_seat_id_104b595d_fk_screenings_seat_id; Type: FK CONSTRAINT; Schema: public; Owner: cinema
--

ALTER TABLE ONLY public.screenings_ticket
    ADD CONSTRAINT screenings_ticket_seat_id_104b595d_fk_screenings_seat_id FOREIGN KEY (seat_id) REFERENCES public.screenings_seat(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict qbh3NDyftPTdEsGg1OJ55Dj4ar9QxZuSgcDfxQAXq2PeYZNc6Fbj1qk5oOWOfmz

